string name = "Bob";
int num = 3;
float point = 34.4F;
Console.Write("Hello, ");
Console.Write(name);
Console.Write("! You have 3 messages in your inbox.");
Console.Write(" The temprature is ");
Console.Write(point);
Console.WriteLine(" celsius.");
Console.Write("Hello, Bob! You have 3 messages in your inbox. The temperature is 34.4 celsius.");